### ISSUE TITLE
Main panel (with title, comments, etc.) is very thin and not shown correctly

### ISSUE THREAD

**Issue by TheFrankyDoll** [MengeTM/YouTube-Layout#1]
Hello! I really like the goal of your extension, but it seems that it is no longer working properly. There are a few bugs, but the most noticeable one is that main panel is extremely thin. I tested it in both Chromium and Firefox.

I'm not a web developer, but I found that a dirty fix would be to add `height: max-content;` to `ytd-watch-grid #primary #secondary-inner` your style.css - this allows the content to be visible and page to be scrollable, but now there is no scroll if mouse is in main panel and video feed does not scroll either. 

Unfortunately I'm incompetent to fix those issues myself and create a proper pull request, so I hope you will patch this extension to work with current youtube design.

**Comment by MengeTM** [comment]
Thank you very much for your feedback. Apologies for the delay of my replay, it seems that I did set up my email notifications wrongly. The new version 1.3 should have fixed the bug. YouTube is pushing out its updates not to all users at once, and I did get the new update today. YouTube seems to still work on the new layout, and the information of the new DOM structure is important for adapting the add-on, which makes it difficult to adapt. Please reply, if there are still bugs, have a nice day :).
